name: Linux

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - '8.1'
          - '8.0'
          - '7.4'
          - '7.4-zts'
        image: [php]
        include:
          - php: '8.1-zts'
            image: ghcr.io/kjdev/php
          - php: '8.0-zts'
            image: ghcr.io/kjdev/php
          - php: '7.3'
            image: ghcr.io/kjdev/php
          - php: '7.2'
            image: ghcr.io/kjdev/php
          - php: '7.1'
            image: ghcr.io/kjdev/php
          - php: '7.0'
            image: ghcr.io/kjdev/php

    if: contains(github.event.head_commit.message, 'ci skip') == false

    container:
      image: ${{ matrix.image }}:${{ matrix.php }}-alpine

    steps:
      - name: Prepare required command
        run: |
          apk upgrade --no-cache
          apk add --no-cache autoconf bison flex gcc git jq-dev libtool make musl-dev
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build
        run: |
          phpize
          ./configure
          make

      - name: Test
        run: |
          make test TESTS="--show-diff" | tee test-output.txt
          grep 'TEST SUMMARY$' test-output.txt > /dev/null && exit 1 || exit 0
        env:
          REPORT_EXIT_STATUS: 1
          NO_INTERACTION: 1
      - name: Failure Test
        run: |
          for FILE in $(find ./tests -name '*.diff'); do
            echo echo $FILE
            cat $FILE
            echo
          done
        if: ${{ failure() }}
